# Generated by 'nixos-generate-config' and updated with btrfs mount options.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "uas" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/97ef2f08-df9c-46f9-8cb6-7ef6f0b19bfb";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/97ef2f08-df9c-46f9-8cb6-7ef6f0b19bfb";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/97ef2f08-df9c-46f9-8cb6-7ef6f0b19bfb";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/97ef2f08-df9c-46f9-8cb6-7ef6f0b19bfb";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "compress=zstd" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/97ef2f08-df9c-46f9-8cb6-7ef6f0b19bfb";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd" "noatime" ];
    };

  # XBOOTLDR partition: kernels and boot entries go here (1GB FAT32, sda4)
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2175-A796";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # ESP: only systemd-boot EFI binary goes here (32MB Ventoy EFI, sda2)
  # Mounted at /efi (not /boot/efi) to avoid FAT32 case-insensitivity
  # conflict between /boot/EFI (XBOOTLDR kernels) and /boot/efi (ESP mount)
  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/EA6C-95B2";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
