###################
#### AUTOSTART ####
###################

# Plugins Baby
exec-once = hyprpm reload -n

# idle manager
# exec-once = hypridle

# wallpaper
exec-once = swww-daemon
exec-once = ~/.config/rofi/menus/swww.sh

# status bar
exec-once = waybar

# pyprland plugin support
exec-once = pypr

# clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch ~/.config/hypr/scripts/image-copy-notify.sh

# polkit authentication service (required to authenticate kde apps)
exec-once = systemctl --user start plasma-polkit-agent
