####################
### KEYBINDINGSS ###
####################

# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier

# General binds
bind = $mainMod, backslash, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, B, exec, $browser
bind = $mainMod SHIFT, B, exec, $browser_private
bind = $mainMod SHIFT, P, exec, $colorPicker
bind = $mainMod, N, exec, $notifications
bind = $mainMod, R, exec, $drun
bind = $mainMod SHIFT, E, exec, rofi -show emoji -theme ~/.config/rofi/styles/emoji.rasi
bind = $mainMod SHIFT, W, exec, $swww
bind = $mainMod SHIFT, C, exec, $clipboard
bind = $mainMod ALT, P, exec, $powerMenu

bind = $mainMod SHIFT, R, exec, killall waybar && waybar &! # restart waybar

bind = $mainMod, V, togglefloating,
bind = $mainMod SHIFT, V, exec, hyprctl dispatch workspaceopt allfloat # toggle all float

bind = $mainMod, F, fullscreen, 1 # waybar will be visible
bind = $mainMod SHIFT, F, fullscreen, 0 # absolute fullscreen
bind = $mainMod CTRL, F, fullscreenstate, 0 2


bind = $mainMod SHIFT, Q, killactive,

# Resizing windows with mainMod + arrows
binde = $mainMod, right, resizeactive, 25 0
binde = $mainMod, left, resizeactive, -25 0
binde = $mainMod, up, resizeactive, 0 -25
binde = $mainMod, down, resizeactive, 0 25

# Move focus with win + hjkl
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = ALT, Tab, cyclenext,
bind = ALT, Tab, bringactivetotop,

# Move windows with winMod+shift+hjkl
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, split:workspace, 1
bind = $mainMod, 2, split:workspace, 2
bind = $mainMod, 3, split:workspace, 3
bind = $mainMod, 4, split:workspace, 4
bind = $mainMod, 5, split:workspace, 5
bind = $mainMod, 6, split:workspace, 6
bind = $mainMod, 7, split:workspace, 7
bind = $mainMod, 8, split:workspace, 8
bind = $mainMod, 9, split:workspace, 9
bind = $mainMod, 0, split:workspace, 10

binds {  # !important https://www.reddit.com/r/hyprland/comments/zyrrtp/how_do_i_switch_back_and_forth_between_two/
    allow_workspace_cycles = true
}

# Lock screen
bind = $mainMod ALT, L, exec, loginctl lock-session

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, split:movetoworkspace, 1
bind = $mainMod SHIFT, 2, split:movetoworkspace, 2
bind = $mainMod SHIFT, 3, split:movetoworkspace, 3
bind = $mainMod SHIFT, 4, split:movetoworkspace, 4
bind = $mainMod SHIFT, 5, split:movetoworkspace, 5
bind = $mainMod SHIFT, 6, split:movetoworkspace, 6
bind = $mainMod SHIFT, 7, split:movetoworkspace, 7
bind = $mainMod SHIFT, 8, split:movetoworkspace, 8
bind = $mainMod SHIFT, 9, split:movetoworkspace, 9
bind = $mainMod SHIFT, 0, split:movetoworkspace, 10


# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace,
bind = $mainMod SHIFT, S, movetoworkspace, special
bind = $mainMod, P, exec, pypr toggle terminal && hyprctl dispatch bringactivetotop

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# ScreenShot
bindl = CTRLSHIFT, P, exec, hyprshot -s -m active -m window # active window
bindl = CTRL, P, exec, hyprshot -s -m region # custom area

# Start spamming shift with SUPERSHIFT+T
bind = $mainMod SHIFT, T, exec, bash -c "pgrep -f spam-shift.sh >/dev/null || ~/.config/hypr/scripts/spam-shift.sh &"

# Kill the spammer with SUPERSHIFT+Y
bind = $mainMod SHIFT, Y, exec, pkill -f spam-shift.sh


# Very specific Binds
# bind = $mainMod CTRL, M, exec, hyprctl keyword master:no_gaps_when_only 1
