#!/bin/sh

alias ls='exa'
alias l='ls -lah'
alias g='lazygit'
alias v="nvim"
alias e="emacs -nw"
alias m="ncmpcpp"


alias grep='grep --color=auto'

alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'


alias tracert="traceroute"

alias pacman="yay"
alias upgrade="yay -Syu"
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)' 

alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

alias distro='cat /etc/*-release'
alias myip='curl ipv4.icanhazip.com'

alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

