set colorscheme dracula

# Show hostname in titlebar?
set hostname_in_titlebar true

set preview_images true
set preview_images_method w3m

# Show hidden files? You can toggle this by typing 'zh'
set show_hidden true

