vim.g.mapleader        = " "
vim.opt.shada          = "%,<50,'25,/25,:20,s20,h,f1"
vim.opt.wrap           = true
vim.opt.list           = true
vim.opt.listchars      = { trail = "•", tab = "  ", extends = "", precedes = "" }
vim.opt.fillchars      = [[eob: ,fold: ,foldopen:▼,foldsep: ,foldclose:▶]]
vim.opt.scrolloff      = 5
vim.opt.whichwrap:append "<,>,[,]"
vim.opt.title          = true
vim.opt.clipboard      = "unnamedplus"
vim.opt.cmdheight      = 0
vim.opt.smartindent    = true
vim.opt.tabstop        = 4
vim.opt.signcolumn     = "auto" -- "yes"
vim.opt.foldcolumn     = "auto" -- "yes"
vim.opt.shiftwidth     = 4
vim.opt.shortmess:append("sI")
vim.opt.smartcase      = true
vim.opt.ignorecase     = true
vim.opt.number         = true
vim.opt.relativenumber = true
vim.opt.colorcolumn    = "80"
vim.opt.cursorline     = true
vim.opt.splitbelow     = true
vim.opt.splitright     = true
vim.opt.termguicolors  = true
vim.opt.timeoutlen     = 750
vim.opt.updatetime     = 250
vim.opt.undofile       = true
vim.opt.undolevels     = 500
vim.opt.undoreload     = 200
vim.opt.shell          = "/bin/bash"
vim.opt.lazyredraw     = false
vim.opt.mouse          = "a"
vim.opt.mousemoveevent = true
vim.opt.pumheight      = 12
vim.opt.pumblend       = 8
vim.opt.completeopt    = "menu,menuone,noselect"
vim.opt.showmode       = false
vim.opt.confirm        = true
vim.opt.laststatus     = 0
vim.opt.guicursor      = "n:block-nCursor-blinkon0,i-ci:ver30-iCursor-blinkon0,v-ve:block-vCursor-blinkon0,o:hor30-oCursor-blinkon0,r-cr:block-rCursor-blinkon0"
vim.opt.wildignore     = { '*.o', '*.a', '__pycache__', '.git', '.svn' }
