#!/usr/bin/env sh
# terminal emulator
super + Return
    alacritty 

# program launcher
super + r 
    rofi -modes "drun,window,run" -show drun

# alt + Tab
#     rofi -show window

# make sxhkd reload its configuration files:
super + Escape
    pkill -USR1 -x sxhkd && dunstify "sxhkd" "Reloaded successfully"

# hide window
super + v
    bspc node -g hidden

# unhide window
super + shift + v
    bspc node {,$(bspc query -N -n .hidden | tail -n1)} -g hidden=off

# unhide window with rofi
super + alt + v
    ~/dotfiles/scripts/unhidewindow
V
# hide/unhide all windows
super + d
    bspc query -N -n .local.window | xargs -I ID bspc node ID -g hidden

# focus a floating window from a tiled window
super + a
    if [ "$(bspc query -N -n focused.floating)" ]; then \
        bspc node -f last.tiled.local; \
    else \
        bspc node -f last.floating.local; \
    fi

# quit/restart bspwm
super + alt + {q,r}
    bspc {quit,wm -r}

super + {_,shift + }q
    bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
    bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
    bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest window
super + g
    bspc node -s biggest.window

#
# state/flags
#

# toggle the window state

super + shift + f 
  bspc node -t fullscreen

super + shift + t
  bspc node -t tiled

super + shift + s 
  bspc node -t floating

# super + {t,shift + t,s,f}
#     bspc node -t ~{tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
    bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#
 


# focus or send to the given desktop
super + {_,shift + }{1-9,0}
    bspc {desktop -f,node -d} 'pointed:^{1-9,10}'

#
# preselect/receptacle
#
# move/resize
#

# move a floating window
super + {Left,Down,Up,Right}
    bspc node -v {-30 0,0 30,0 -30,30 0}

# screenshot
super + p 
    flameshot gui 

# make split ratios equal
super + equal
    bspc node @/ --equalize

# make split ratios balanced
super + minus
    bspc node @/ --balance

XF86AudioPlay
  playerctl play-pause


