#! /bin/bash

pgrep -x polybar > /dev/null || polybar &
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &
pgrep -x picom > /dev/null || picom --config ~/.config/bspwm/picom.conf &
feh --no-fehbg --bg-scale ~/.config/bspwm/wallpaper.jpg


bspc config border_width        0
bspc config window_gap          7
bspc config focus_follows_pointer true
bspc config focused_border_color "#B48EAD"
bspc config normal_border_color "#000000"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
